import json
import os
import re

# File paths — configurable via env vars (.env) hoặc đường dẫn tương đối
# Ví dụ .env: ACTIVITY_FILE=./input/activity.txt, ECONOMY_FILE=./input/economy.txt
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

ACTIVITY_FILE = os.getenv(
    "ACTIVITY_FILE",
    str(SCRIPT_DIR / "input" / "activity_output.txt"),
)
ECONOMY_FILE = os.getenv(
    "ECONOMY_FILE",
    str(SCRIPT_DIR / "input" / "economy_output.txt"),
)
MIGRATION_SQL_PATH = os.getenv(
    "MIGRATION_SQL_PATH",
    str(SCRIPT_DIR / "migration.sql"),
)

def extract_json_from_step_output(filepath):
    if not os.path.exists(filepath):
        print(f"Error: file not found: {filepath}")
        return []
    
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    result_text = data.get("result", "")
    match = re.search(r'<untrusted-data-[^>]+>\s*(.*?)\s*</untrusted-data-[^>]+>', result_text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except Exception as e:
            print(f"Error decoding JSON from match: {e}")
            return []
    else:
        print("No untrusted-data tags found.")
        return []

def main():
    print("Reading step output files...")
    activities = extract_json_from_step_output(ACTIVITY_FILE)
    economies = extract_json_from_step_output(ECONOMY_FILE)
    
    print(f"Loaded {len(activities)} user_activity records.")
    print(f"Loaded {len(economies)} user_economy records.")
    
    sql_lines = []
    
    # 1. Add schema drop/create statements
    sql_lines.append("-- SQL Migration Script: Seoul to Singapore")
    sql_lines.append("-- Generated by generate_migration_sql.py\n")
    
    # Tables list and their creation SQL
    tables_ddl = """
-- 1. Table: guild_config
CREATE TABLE IF NOT EXISTS public.guild_config (
    guild_id text PRIMARY KEY,
    is_onboard_enabled boolean DEFAULT true,
    apply_channel_id text,
    member_role_id text,
    officer_role_id text,
    rules_channel_id text,
    chat_channel_id text,
    question_channel_id text
);
ALTER TABLE public.guild_config ENABLE ROW LEVEL SECURITY;

-- 2. Table: ai_config
CREATE TABLE IF NOT EXISTS public.ai_config (
    guild_id text PRIMARY KEY,
    model text,
    available_models jsonb DEFAULT '[]'::jsonb,
    channel_buffers jsonb DEFAULT '{}'::jsonb,
    intercept_channels jsonb DEFAULT '[]'::jsonb,
    autowiki_channels jsonb DEFAULT '[]'::jsonb,
    updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.ai_config ENABLE ROW LEVEL SECURITY;

-- 3. Table: user_activity
CREATE TABLE IF NOT EXISTS public.user_activity (
    user_id text PRIMARY KEY,
    last_seen text,
    updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.user_activity ENABLE ROW LEVEL SECURITY;

-- 4. Table: user_economy
CREATE TABLE IF NOT EXISTS public.user_economy (
    user_id text PRIMARY KEY,
    silver_pieces integer DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.user_economy ENABLE ROW LEVEL SECURITY;

-- 5. Table: sp_metadata
CREATE TABLE IF NOT EXISTS public.sp_metadata (
    id integer PRIMARY KEY DEFAULT 1,
    last_update text DEFAULT 'Chưa có dữ liệu'::text
);
ALTER TABLE public.sp_metadata ENABLE ROW LEVEL SECURITY;

-- 6. Table: alo_tts_config
CREATE TABLE IF NOT EXISTS public.alo_tts_config (
    id integer PRIMARY KEY DEFAULT 1,
    read_name jsonb DEFAULT '{}'::jsonb,
    rejoin jsonb DEFAULT '{}'::jsonb,
    afk jsonb DEFAULT '{}'::jsonb
);
ALTER TABLE public.alo_tts_config ENABLE ROW LEVEL SECURITY;

-- 7. Table: json_storage
CREATE TABLE IF NOT EXISTS public.json_storage (
    file_name text PRIMARY KEY,
    data jsonb DEFAULT '{}'::jsonb
);
ALTER TABLE public.json_storage ENABLE ROW LEVEL SECURITY;
"""
    sql_lines.append(tables_ddl)
    
    # 2. Insert constant data
    # sp_metadata
    sql_lines.append("\n-- Insert data for public.sp_metadata")
    sql_lines.append("INSERT INTO public.sp_metadata (id, last_update) VALUES (1, '2026-07-06 20:12:04') ON CONFLICT (id) DO UPDATE SET last_update = EXCLUDED.last_update;")
    
    # alo_tts_config
    sql_lines.append("\n-- Insert data for public.alo_tts_config")
    sql_lines.append("INSERT INTO public.alo_tts_config (id, read_name, rejoin, afk) VALUES (1, '{\"712258265769050164\":true}'::jsonb, '{}'::jsonb, '{}'::jsonb) ON CONFLICT (id) DO UPDATE SET read_name = EXCLUDED.read_name, rejoin = EXCLUDED.rejoin, afk = EXCLUDED.afk;")
    
    # ai_config
    sql_lines.append("\n-- Insert data for public.ai_config")
    available_models_json = json.dumps([
        "google/gemini-3.5-flash-lite", "google/gemini-3.1-flash-lite", "google/gemma-4-31b-it",
        "nvidia/nemotron-3-ultra-550b-a55b:free", "nvidia/nemotron-3-super-120b-a12b:free",
        "poolside/laguna-s-2.1:free", "inclusionai/ling-3.0-flash:free", "cohere/north-mini-code:free"
    ])
    sql_lines.append(
        f"INSERT INTO public.ai_config (guild_id, model, available_models, channel_buffers, intercept_channels, autowiki_channels, updated_at) "
        f"VALUES ('default', 'inclusionai/ling-3.0-flash:free', '{available_models_json}'::jsonb, '{{}}'::jsonb, '[]'::jsonb, '[]'::jsonb, '2026-08-03 20:21:19.112499+00') "
        f"ON CONFLICT (guild_id) DO UPDATE SET model = EXCLUDED.model, available_models = EXCLUDED.available_models, channel_buffers = EXCLUDED.channel_buffers, intercept_channels = EXCLUDED.intercept_channels, autowiki_channels = EXCLUDED.autowiki_channels, updated_at = EXCLUDED.updated_at;"
    )
    
    # 3. Insert user_activity
    if activities:
        sql_lines.append("\n-- Insert data for public.user_activity")
        for act in activities:
            user_id = act["user_id"]
            last_seen = act["last_seen"]
            updated_at = act["updated_at"]
            # escape single quotes in last_seen if any
            last_seen_val = f"'{last_seen}'" if last_seen else "NULL"
            sql_lines.append(
                f"INSERT INTO public.user_activity (user_id, last_seen, updated_at) "
                f"VALUES ('{user_id}', {last_seen_val}, '{updated_at}') "
                f"ON CONFLICT (user_id) DO UPDATE SET last_seen = EXCLUDED.last_seen, updated_at = EXCLUDED.updated_at;"
            )
            
    # 4. Insert user_economy
    if economies:
        sql_lines.append("\n-- Insert data for public.user_economy")
        for eco in economies:
            user_id = eco["user_id"]
            silver_pieces = eco["silver_pieces"]
            updated_at = eco["updated_at"]
            sql_lines.append(
                f"INSERT INTO public.user_economy (user_id, silver_pieces, updated_at) "
                f"VALUES ('{user_id}', {silver_pieces}, '{updated_at}') "
                f"ON CONFLICT (user_id) DO UPDATE SET silver_pieces = EXCLUDED.silver_pieces, updated_at = EXCLUDED.updated_at;"
            )
            
    # Write migration.sql
    with open(MIGRATION_SQL_PATH, 'w', encoding='utf-8') as f:
        f.write("\n".join(sql_lines))
    print(f"Successfully generated migration script at: {MIGRATION_SQL_PATH}")

if __name__ == "__main__":
    main()
